/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import gymyang.Gymyang;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import modelo.Monitor;

/**
 * Panel para mostrar un monitor
 * @author Adrián
 */
public class MonitorPanel extends javax.swing.JPanel {

    private Monitor monitor;
    
    /**
     * Creates new form Monitor
     */
    public MonitorPanel(Monitor monitor) {
        initComponents();
        this.monitor = monitor;
        jButtonModificar.setVisible(false);
        if (Gymyang.usuarioActual.getNombre().equals("admin")) {
            jButtonModificar.setVisible(true);
        }
        Image img = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/META-INF/modificar.png"));
        jButtonModificar.setIcon(new ImageIcon(img.getScaledInstance(40, 34, Image.SCALE_SMOOTH)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelImagen = new javax.swing.JLabel();
        jLabelNombreApellidos = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jLabelFrase = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jButtonModificar = new javax.swing.JButton();

        jLabelNombreApellidos.setText("jLabel2");

        jLabelEdad.setText("jLabel1");

        jLabelFrase.setText("jLabel1");

        jLabelDescripcion.setText("jLabel1");

        jButtonModificar.setMaximumSize(new java.awt.Dimension(40, 34));
        jButtonModificar.setMinimumSize(new java.awt.Dimension(40, 34));
        jButtonModificar.setPreferredSize(new java.awt.Dimension(40, 34));
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .addComponent(jLabelFrase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelEdad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNombreApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelNombreApellidos)
                            .addComponent(jButtonModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEdad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFrase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        AgnadirMonitor a = new AgnadirMonitor();
        a.setTitle("Modificar/Eliminar Monitor");
        a.jButtonEliminar.setVisible(true);
        a.jButtonAgnadir.setText("Modificar");
        a.jTextFieldNombre.setText(monitor.getNombre());
        a.jTextFieldApellidos.setText(monitor.getApellidos());
        a.jSpinnerEdad.setValue(monitor.getEdad());
        a.jTextFieldFrase.setText(monitor.getFrase());
        a.jTextAreaDescripcion.setText(monitor.getDescripcion());
        a.monitor = monitor;
        a.setVisible(true);
    }//GEN-LAST:event_jButtonModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonModificar;
    public javax.swing.JLabel jLabelDescripcion;
    public javax.swing.JLabel jLabelEdad;
    public javax.swing.JLabel jLabelFrase;
    public javax.swing.JLabel jLabelImagen;
    public javax.swing.JLabel jLabelNombreApellidos;
    // End of variables declaration//GEN-END:variables
}
