/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaz;

import javax.swing.JScrollPane;

/**
 *
 * @author alumnoDAM
 */
public class Principal extends javax.swing.JFrame {
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        jPanelPrincipal.removeAll();
        jPanelPrincipal.add(new JScrollPane(new Inicio()));
        jPanelPrincipal.repaint();
        jPanelPrincipal.revalidate();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuInicio = new javax.swing.JMenu();
        jMenuInstalaciones = new javax.swing.JMenu();
        jMenuClases = new javax.swing.JMenu();
        jMenuMonitores = new javax.swing.JMenu();
        jMenuPerfil = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(815, 600));
        setMinimumSize(new java.awt.Dimension(815, 600));
        setPreferredSize(new java.awt.Dimension(815, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(815, 600));

        jPanelPrincipal.setPreferredSize(new java.awt.Dimension(795, 420));
        jPanelPrincipal.setLayout(new java.awt.CardLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/META-INF/cintas_de_correr800x450.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(810, 150));
        jLabel1.setMinimumSize(new java.awt.Dimension(810, 150));
        jLabel1.setPreferredSize(new java.awt.Dimension(810, 150));

        jMenuBar1.setMinimumSize(new java.awt.Dimension(234, 30));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(234, 30));

        jMenuInicio.setText("Inicio");
        jMenuInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuInicioMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuInicio);

        jMenuInstalaciones.setText("Instalaciones");
        jMenuInstalaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuInstalacionesMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuInstalaciones);

        jMenuClases.setText("Clases");
        jMenuClases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuClasesMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuClases);

        jMenuMonitores.setText("Monitores");
        jMenuMonitores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuMonitoresMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuMonitores);

        jMenuPerfil.setText("Perfil");
        jMenuPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuPerfilMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuPerfil);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuInstalacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuInstalacionesMouseClicked
        jPanelPrincipal.removeAll();
        jPanelPrincipal.add(new JScrollPane(new Instalaciones()));
        jPanelPrincipal.repaint();
        jPanelPrincipal.revalidate();
        
    }//GEN-LAST:event_jMenuInstalacionesMouseClicked

    private void jMenuClasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuClasesMouseClicked
        jPanelPrincipal.removeAll();
        jPanelPrincipal.add(new JScrollPane(new Clases()));
        jPanelPrincipal.repaint();
        jPanelPrincipal.revalidate();
    }//GEN-LAST:event_jMenuClasesMouseClicked

    private void jMenuInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuInicioMouseClicked
        jPanelPrincipal.removeAll();
        jPanelPrincipal.add(new JScrollPane(new Inicio()));
        jPanelPrincipal.repaint();
        jPanelPrincipal.revalidate();
    }//GEN-LAST:event_jMenuInicioMouseClicked

    private void jMenuMonitoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuMonitoresMouseClicked
        jPanelPrincipal.removeAll();
        jPanelPrincipal.add(new JScrollPane(new Monitores()));
        jPanelPrincipal.repaint();
        jPanelPrincipal.revalidate();
    }//GEN-LAST:event_jMenuMonitoresMouseClicked

    private void jMenuPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuPerfilMouseClicked
        jPanelPrincipal.removeAll();
        jPanelPrincipal.add(new JScrollPane(new Perfil()));
        jPanelPrincipal.repaint();
        jPanelPrincipal.revalidate();
    }//GEN-LAST:event_jMenuPerfilMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuClases;
    private javax.swing.JMenu jMenuInicio;
    private javax.swing.JMenu jMenuInstalaciones;
    private javax.swing.JMenu jMenuMonitores;
    public javax.swing.JMenu jMenuPerfil;
    private javax.swing.JPanel jPanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
